version: 0.2

env:
  variables:
    CLIENT_BRANCH: "GST"  # Set to "GST" or "Restaurant" based on your requirement

phases:
  install:
    commands:
      - echo "Installing necessary dependencies"
      - apt-get update && apt-get install -y git

  pre_build:
    commands:
      - echo "Cloning Community repo..."
      - git clone https://github.com/madhukamath29/demo-odoo17.git 

      - echo "Cloning Third-party addons from Inv-repo..."
      - git clone --branch Third-party-addon https://github.com/madhukamath29/INV-Repo.git third-party-repo

      - echo "Cloning Common addons from Inv-repo..."
      - git clone --branch common-addon https://github.com/madhukamath29/INV-Repo.git common-addon-repo

      # Clone GST or Restaurant based on the variable
      - echo "Cloning client-specific addons (GST/Restaurant)..."
      - |
        if [ "$CLIENT_BRANCH" == "GST" ]; then
          git clone --branch gst https://github.com/yourusername/inv-repo.git client-addon-repo
        elif [ "$CLIENT_BRANCH" == "Restaurant" ]; then
          git clone --branch restaurant https://github.com/yourusername/inv-repo.git client-addon-repo
        
  build:
    commands:
      - echo "Merging the necessary repositories into one directory..."
      - mkdir -p merged-addons
      - cp -r community-repo/* merged-addons/
      - cp -r third-party-repo/* merged-addons/
      - cp -r common-addon-repo/* merged-addons/
      - cp -r client-addon-repo/* merged-addons/

      # Move merged files to the appropriate directory based on the branch
      - echo "Moving merged files to the appropriate directory..."
      - |
        if [ "$CLIENT_BRANCH" == "GST" ]; then
          mkdir -p merged-addons/GST
          mv merged-addons/* merged-addons/GST/
        elif [ "$CLIENT_BRANCH" == "Restaurant" ]; then
          mkdir -p merged-addons/Restaurant
          mv merged-addons/* merged-addons/Restaurant/
        fi

  post_build:
    commands:
      - echo "Build complete, files merged."

artifacts:
  files:
    - '**/*'  # Upload all merged files from the merged-addons directory

  base-directory: merged-addons  # Set the base directory for artifacts
