version: 0.2

phases:
  install:
    commands:
      - echo "Installing necessary dependencies"
      - apt-get update && apt-get install -y git

  pre_build:
    commands:
      - echo "Cloning Community repo..."
      - git clone https://github.com/madhukamath29/demo-odoo17.git community-repo

      - echo "Cloning Third-party addons from Inv-repo..."
      - git clone --branch Third-party-addon https://github.com/madhukamath29/INV-Repo.git third-party-repo

      - echo "Cloning Common addons from Inv-repo..."
      - git clone --branch common-addon https://github.com/madhukamath29/INV-Repo.git common-addon-repo

      - echo "Cloning Restaurant branch from Inv-repo...."
      - git clone --branch Restaurent-community --single-branch https://github.com/madhukamath29/INV-Repo.git restaurent-repo  # Replace with the correct repository URL if necessary

  build:
    commands:
      - echo "Merging the necessary repositories into one directory..."
      - mkdir -p merged-addons
      - cp -r community-repo/* merged-addons/
      - cp -r enterprise-repo/* merged-addons/
      - cp -r third-party-repo/* merged-addons/
      - cp -r common-addon-repo/* merged-addons/
      - cp -r restaurent-repo/* merged-addons/ 

      # Move merged files to the appropriate directory based on the branch
      - echo "Moving merged files to the appropriate directory..."

  post_build:
    commands:
      - echo "Build complete, files merged."

artifacts:
  files:
    - '**/*'  # Upload all merged files from the merged-addons directory

  base-directory: merged-addons  # Set the base directory for artifacts
