version: 0.2

phases:
  install:
    commands:
      - echo "Installing necessary dependencies"
      - apt-get update && apt-get install -y git 

  pre_build:
    commands:
      - echo "Fetching the Personal Access Token from Parameter Store..."
      # Fetching the Personal Access Token and exporting it as an environment variable
      - export GITHUB_TOKEN=$(aws ssm get-parameter --name "PAT-Enterprise" --with-decryption --query "Parameter.Value" --output text)

      - echo "Cloning Community repo...."
      - git clone https://github.com/madhukamath29/demo-odoo17.git community-repo

      - echo "Cloning Enterprise repo..."
      # Use the token for authentication in the clone command
      - git clone https://$GITHUB_TOKEN@github.com/madhukamath29/enterprise_repo.git enterprise-repo

      - echo "Cloning Third-party addons from Inv-repo..."
      - git clone --branch Third-party-addon https://github.com/madhukamath29/INV-Repo.git third-party-repo

      - echo "Cloning Common addons from Inv-repo..."
      - git clone --branch common-addon https://github.com/madhukamath29/INV-Repo.git common-addon-repo

      - echo "Cloning GST branch from Inv-repo..."
      - git clone --branch GST-Enterprise --single-branch https://github.com/madhukamath29/INV-Repo.git gst-repo

  build:
    commands:
      - echo "Merging the necessary repositories into one directory...."
      - mkdir -p merged-addons
      - cp -r community-repo/* merged-addons/
      - cp -r enterprise-repo/* merged-addons/
      - cp -r third-party-repo/* merged-addons/
      - cp -r common-addon-repo/* merged-addons/
      - cp -r gst-repo/* merged-addons/  

      # Move merged files to the appropriate directory based on the branch
      - echo "Moving merged files to the appropriate directory..."

  post_build:
    commands:
      - echo "Build complete, files merged..."

artifacts:
  files:
    - '**/*'  

  base-directory: merged-addons
